- libyang/data.py
- tests/test_data.py
Depending on the Python version and/or the way that dictionaries are created and stored, the iteration order of keys is neither stable nor predictable.
For instance, the unit tests do not work on python 3.5 because the [creation order of the dictionary keys iteration is only preserved since python 3.6](https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation). Before that, it is random. They work on other versions of python because the dictionaries are actually defined with the keys first and in the correct order.
However, libyang requires that the first children of a list node are its keys and they must be in the order defined in the YANG schema. When a data tree has a key in the wrong position, we get an error during lyd_validate:
```
Missing required element "keyname" in …
```
> data: fix invalid key ordering in dict_to_dnode

- libyang/data.py
- libyang/schema.py
- tests/test_data.py
- tox-install.sh
There is a typo. However, now that I fixed it, the validation fails complaining about a missing required element that is not even present in the test YANG schema.
```
Missing required element "notification" in "duration".
```
I must have misunderstood the use of the `LYD_OPT_RPCREPLY` flag for `lyd_validate()`. @michalvasko can you shine some light on this? Can you tell me what I am doing wrong?
> Fix dict conversion for rpcs

- cffi/cdefs.h
- libyang/data.py
- tests/test_data.py
The `find_one` and `find_all` method does not work due to the following error: 
```
AttributeError: cdata 'struct ly_set *' has no field 'd'
```
I fixed the issue and added a test for the `find_one` method.
> Fix find_all function and add test for it

- README.rst
Fix the following error when running the data tree example provided in README:
```
LibyangError: validation failed: Missing required element "content-id" in "yang-library".
```
When parsing a config tree, we do not have the complete datastore available (no ietf-yang-library.yang module data).
Link: https://github.com/CESNET/libyang-python/blob/v1.6.1/libyang/schema.py#L154-L155
Link: https://netopeer.liberouter.org/doc/libyang/master/html/group__parseroptions.html
Fixes: #21
> README: fix data tree example

- tests/test_data.py
We are using the target > running node without enabling the needed
features.
This patch enable features for ietf-netconf module.
> tests: fix rpc test

- libyang/data.py
- tests/test_data.py
When using sysrepo, we need to use sysrepo function to free dnode data.
Currently, the free method can't be overridden without hack.
This patch add the possibility to override the free method and will
allow the utilization with sysrepo-python.
> data: allow to customize free

- libyang/context.py
- tests/test_context.py
search_dirs can contain duplicate path if YANGPATH envvar is used.
With libyang1, we can add several time the same searchdir without
problem but with libyang2, ly_ctx_set_searchdir returns an error if we
add a path already existant.
To fix it, we now pass the search dir directly when creating the
context.
> context: fix duplicate path error

- libyang/data.py
Currently, if we use the free_func feature, we can't call the free
method (similary to a parent method). If we do, we enter in an infinite
loop.
This patch allows to call free_internal from the free_func in order to
avoid infinite loop.
> data: update free method

- libyang/schema.py
- tests/test_diff.py
- tests/test_schema.py
- tests/yang/yolo/yolo-system.yang
Accessing feature states is useful to enable/disable leafs.
However, when a if-feature contain a condition (not/or/and keywords),
there is currently no way to get the state resulting of the expression.
Add a state method to all IfFeatureExpr objects so a state of the
entire if-feature expression can be evaluated.
Test all basic cases (one operator).
> schema: add state method for conditional if-features

- libyang/data.py
In a SList, if you have a key not in str type (uint16 for example), the
str2c function will not manage to convert it to cdata str because it
waits only for str type.
So we force str type in order to fix this problem.
> data: force key_values to str

- libyang/schema.py
Currently, we use the compiled schema to retrieve the ordered state. It
can't work since with the compiled node, it will always return True. In
order to have the good behavior, we have to use the parsed schema.
> schema: fix ordered return value

- libyang/xpath.py
- tests/test_xpath.py
There is no reason to remove the '\' in a key name if they are not
escaping a quote. Leave them untouched.
> xpath: properly process key names with \ in xpath_split

- cffi/cdefs.h
- libyang/context.py
Today, loading modules in a context is very slow, because each time a
module is added, the whole schema is recompiled. Libyang has a flag to
defer the compilation to a later ly_ctx_compile call. Let's expose
this feature.
> context: add explicit_compile option

- libyang/schema.py
Sometimes, cdata_parsed is None. Check it before using it, as we do in
the other functions using cdata_parsed.
It fixes this error:
AttributeError: 'NoneType' object has no attribute 'range'
> schema: check cdata_parsed before using it

- libyang/schema.py
- tests/test_schema.py
- tests/yang/omg/omg-extensions.yang
- tests/yang/yolo/yolo-system.yang
The ext_size field has been removed with libyang2. Also, there is no parent anymore, the compiled type contains everything needed.
This commit fixes the following error when calling type.extensions():
> File "/(...)/.venv/src/libyang/libyang/schema.py", line 579, in extensions
>   for i in range(self.cdata.ext_size):
> AttributeError: cdata 'struct lysc_type *' has no field 'ext_size'
Fix by using ly_array_count, and add a new test for this case.
> schema: fix type extensions

- libyang/schema.py
- tests/test_schema.py
- tests/yang-old/yolo/yolo-system.yang
- tests/yang/yolo/yolo-system.yang
The libyang lysp_type struct arg.str fields contains the pattern string
+ a character in the beginning telling if the match is inverted or not.
Since the libyang2 port, the patterns function do not take this into
account anymore, and yields this string directly, which is not correct.
The patterns function is supposed to yield Iterator[Tuple[str, bool],
containing the pattern string and a boolean telling if the match is
inverted or not, restore it. Add a test for it as well.
While there, use ly_array_iter.
> schema: fix type patterns return value

- cffi/cdefs.h
- cffi/source.c
The commit 193dacdfac53 ("plugins exts CHANGE ext parsing isolated into a callback") reworked the lysp_ext_instance and lysc_ext_instance structures.
Take it into account.
Link: https://github.com/CESNET/libyang/commit/193dacdfac53
Fixes: https://github.com/CESNET/libyang-python/issues/57
> cffi: update lys[c,p]_ext_instance to libyang 2.1.0

- libyang/data.py
The native dict format is not a 1:1 translation of the JSON format. This was a deliberate design choice to make it easier to work with data nodes in python code. Document the differences.
Fixes: https://github.com/CESNET/libyang-python/issues/60
> data: document differences between the native dict format and json

- libyang/diff.py
When comparing two models including choices/cases, schema_diff will find differences, because the schema are actually different. Add an option to use the node data_paths, which will ignore choice/case.
> diff: add an option to use data_path

- libyang/context.py
- tests/test_data.py
When instantiating a Context without a yang library loading data will trigger the following validation error *unless* the context is instantiated correctly *or* the validation flags `LYD_VALIDATE_NO_STATE` or `LYD_VALIDATE_PRESENT` are used.
```
'Data location "/ietf-yang-library:yang-library".:  Mandatory node
"content-id" instance does not exist.'
```
> Instantiate `ly_ctx_new` with `LY_CTX_NO_YANG_LIB`

- libyang/schema.py
- tests/test_schema.py
There is no way to get a node data path (path without choice/case) without list keys.
Adds the path_type parameter to the SNode.schema_path() method. This parameter can takes 3 values:
- SNode.PATH_LOG: returns the path with schema-only nodes (choice, case) included, the default
- SNode.PATH_DATA: returns the path without schema-only nodes
- SNode.PATH_DATA_PATTERN: similar to PATH_DATA with list keys added (the one used by data_path())
The SNode.PATH_LOG is set by default to not change the original behavior.
The SNode.data_path() method now calls SNode.schema_path() with self.PATH_DATA_PATTERN instead of lib.lysc_path().
Here is an example of the output difference between schema_path(), data_path(), and schema_path(path_type=SNode.PATH_DATA) with a node included in a choice and a list: …
> schema: enable getting node data path without list key

- libyang/xpath.py
- tests/test_xpath.py
This patch adds support for indexed xpath to xpath_set. In the case of a leaf-list, it is now possible to apply xpath_set in this way:
xpath_set(d, "/lstnum[5]", 33, after="4")
This will replace the 5th element of the leaf-list with the new value 33.
This feature is important because libyang can return this type of xpath when a callback is called with sr_module_change_subscribe from sysrepo.
The tests are updated accordingly.
> xpath: add support for indexed xpath

- .github/workflows/ci.yml
- tox.ini
* `envlist` looks for Python 3.9 to 3.13; these are [the ones being supported](https://devguide.python.org/versions/)
* dropped 3.6 to 3.8 from CI/CD tests
* removed `py3`: it is never used, since [first found wins](https://tox.wiki/en/stable/config.html#python-options)
```shell
format
lint
py39
py310
py311
py312
py313
pypy3
lydevel
coverage
```
> tox: bumped Python versions

- libyang/schema.py
- tests/test_data.py
Sometimes it is necessary to store only the data.
Signed-off-by: Jeremie Leska <jeremie.leska@6wind.com>
> schema: add store_only parameter to parse_data_dict

- cffi/cdefs.h
This patch aligns the cdefs definition with the rest of the file structure
> cdefs: Removal of unnecessary variable name defintion

- libyang/schema.py
- tests/test_schema.py
This patch introduces access to nested extensions
> schema: adds nested extensions access

- libyang/context.py
`data_load()` returns a reference to `struct ly_in *` which must be free'd by `lys_in_free()`.  This is done in one of three locations.  This corrects this oversight.
This was found during unit tests of SONiC during porting to libyang3 from libyang 1.0.73.
Signed-off-by: Brad House (@bradh352)
> correct memory leak of `struct ly_in *` objects

- .github/workflows/ci.yml
- check-commits.sh
- libyang/context.py
- tests/test_context.py
This is an attempt to fix #101, however, it doesn't work as expected and I don't know why. Perhaps you can give me a hint?
The issue is how to pass a list of features into the C API. I implemented the helper function `strlist2c` for that purpose based on the example in the ffi documentation: [An example of calling a main-like thing](https://cffi.readthedocs.io/en/latest/using.html#an-example-of-calling-a-main-like-thing)
However, the pointers/memory received by the C API seem not to be valid.
Do you have an idea what's going wrong here?
> Generalize load module
